### PR TITLE
initial commit fo Command Line Interface

### PR DESCRIPTION
**Pull request by nikitaivkin**
Initial commit: 
   1) cli for the following sketches:
          Frequencies, HLL, Quantiles, ReservoirSampling, Theta, VarOptSampling.
   2) added dependency on external apache commons-cli package (needed to parse command line options)
P.S.: added dependency on com.clearspring.analytics and changed the scope of testng package to compile, because could not compile the project otherwise (even before contributing anything)

All the best,
Nikita

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by leerho** [comment]
@nikitaivkin 

Could you please sign the CLA so that we can proceed with the integration.

Thanks

**Comment by nikitaivkin** [comment]
Hi Lee,

I already signed it right after I was notified about it around a week ago.
Here what I get if I follow the link:
[image: Inline image 1]

All the best,
Nikita

**Comment by leerho** [comment]
Oops, sorry, I didn't note the fine print :),  we will merge and fix the underlying compile problems from here.  Thanks!

**Pull request merged**
